// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: mempool.proto

package mempool

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_mempool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_mempool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_mempool_proto_rawDescGZIP(), []int{0}
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicsResponse) Reset() {
	*x = TopicsResponse{}
	mi := &file_mempool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicsResponse) ProtoMessage() {}

func (x *TopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mempool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicsResponse.ProtoReflect.Descriptor instead.
func (*TopicsResponse) Descriptor() ([]byte, []int) {
	return file_mempool_proto_rawDescGZIP(), []int{1}
}

func (x *TopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type TxSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Quantity      uint64                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSend) Reset() {
	*x = TxSend{}
	mi := &file_mempool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSend) ProtoMessage() {}

func (x *TxSend) ProtoReflect() protoreflect.Message {
	mi := &file_mempool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSend.ProtoReflect.Descriptor instead.
func (*TxSend) Descriptor() ([]byte, []int) {
	return file_mempool_proto_rawDescGZIP(), []int{2}
}

func (x *TxSend) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TxSend) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TxSend) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TxSend) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_mempool_proto protoreflect.FileDescriptor

const file_mempool_proto_rawDesc = "" +
	"\n" +
	"\rmempool.proto\x12\tvalidator\x1a\x1bgoogle/protobuf/empty.proto\"\x1b\n" +
	"\x05Topic\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\":\n" +
	"\x0eTopicsResponse\x12(\n" +
	"\x06topics\x18\x01 \x03(\v2\x10.validator.TopicR\x06topics\"f\n" +
	"\x06TxSend\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x04R\bquantity\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature2\xbb\x01\n" +
	"\x0eMemPoolService\x124\n" +
	"\x06Gossip\x12\x10.validator.Topic\x1a\x16.google.protobuf.Empty\"\x00\x12>\n" +
	"\aIndulge\x12\x16.google.protobuf.Empty\x1a\x19.validator.TopicsResponse\"\x00\x123\n" +
	"\x04Send\x12\x11.validator.TxSend\x1a\x16.google.protobuf.Empty\"\x00B\x1cZ\x1aaccretion/internal/mempoolb\x06proto3"

var (
	file_mempool_proto_rawDescOnce sync.Once
	file_mempool_proto_rawDescData []byte
)

func file_mempool_proto_rawDescGZIP() []byte {
	file_mempool_proto_rawDescOnce.Do(func() {
		file_mempool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mempool_proto_rawDesc), len(file_mempool_proto_rawDesc)))
	})
	return file_mempool_proto_rawDescData
}

var file_mempool_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mempool_proto_goTypes = []any{
	(*Topic)(nil),          // 0: validator.Topic
	(*TopicsResponse)(nil), // 1: validator.TopicsResponse
	(*TxSend)(nil),         // 2: validator.TxSend
	(*emptypb.Empty)(nil),  // 3: google.protobuf.Empty
}
var file_mempool_proto_depIdxs = []int32{
	0, // 0: validator.TopicsResponse.topics:type_name -> validator.Topic
	0, // 1: validator.MemPoolService.Gossip:input_type -> validator.Topic
	3, // 2: validator.MemPoolService.Indulge:input_type -> google.protobuf.Empty
	2, // 3: validator.MemPoolService.Send:input_type -> validator.TxSend
	3, // 4: validator.MemPoolService.Gossip:output_type -> google.protobuf.Empty
	1, // 5: validator.MemPoolService.Indulge:output_type -> validator.TopicsResponse
	3, // 6: validator.MemPoolService.Send:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mempool_proto_init() }
func file_mempool_proto_init() {
	if File_mempool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mempool_proto_rawDesc), len(file_mempool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mempool_proto_goTypes,
		DependencyIndexes: file_mempool_proto_depIdxs,
		MessageInfos:      file_mempool_proto_msgTypes,
	}.Build()
	File_mempool_proto = out.File
	file_mempool_proto_goTypes = nil
	file_mempool_proto_depIdxs = nil
}
