// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: mempool.proto

package mempool

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemPoolService_Gossip_FullMethodName  = "/validator.MemPoolService/Gossip"
	MemPoolService_Indulge_FullMethodName = "/validator.MemPoolService/Indulge"
	MemPoolService_Send_FullMethodName    = "/validator.MemPoolService/Send"
)

// MemPoolServiceClient is the client API for MemPoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemPoolServiceClient interface {
	Gossip(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Indulge(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TopicsResponse, error)
	Send(ctx context.Context, in *TxSend, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type memPoolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemPoolServiceClient(cc grpc.ClientConnInterface) MemPoolServiceClient {
	return &memPoolServiceClient{cc}
}

func (c *memPoolServiceClient) Gossip(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MemPoolService_Gossip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memPoolServiceClient) Indulge(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicsResponse)
	err := c.cc.Invoke(ctx, MemPoolService_Indulge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memPoolServiceClient) Send(ctx context.Context, in *TxSend, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MemPoolService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemPoolServiceServer is the server API for MemPoolService service.
// All implementations should embed UnimplementedMemPoolServiceServer
// for forward compatibility.
type MemPoolServiceServer interface {
	Gossip(context.Context, *Topic) (*emptypb.Empty, error)
	Indulge(context.Context, *emptypb.Empty) (*TopicsResponse, error)
	Send(context.Context, *TxSend) (*emptypb.Empty, error)
}

// UnimplementedMemPoolServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemPoolServiceServer struct{}

func (UnimplementedMemPoolServiceServer) Gossip(context.Context, *Topic) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Gossip not implemented")
}
func (UnimplementedMemPoolServiceServer) Indulge(context.Context, *emptypb.Empty) (*TopicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Indulge not implemented")
}
func (UnimplementedMemPoolServiceServer) Send(context.Context, *TxSend) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedMemPoolServiceServer) testEmbeddedByValue() {}

// UnsafeMemPoolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemPoolServiceServer will
// result in compilation errors.
type UnsafeMemPoolServiceServer interface {
	mustEmbedUnimplementedMemPoolServiceServer()
}

func RegisterMemPoolServiceServer(s grpc.ServiceRegistrar, srv MemPoolServiceServer) {
	// If the following call panics, it indicates UnimplementedMemPoolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemPoolService_ServiceDesc, srv)
}

func _MemPoolService_Gossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Topic)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemPoolServiceServer).Gossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemPoolService_Gossip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemPoolServiceServer).Gossip(ctx, req.(*Topic))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemPoolService_Indulge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemPoolServiceServer).Indulge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemPoolService_Indulge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemPoolServiceServer).Indulge(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemPoolService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxSend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemPoolServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemPoolService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemPoolServiceServer).Send(ctx, req.(*TxSend))
	}
	return interceptor(ctx, in, info, handler)
}

// MemPoolService_ServiceDesc is the grpc.ServiceDesc for MemPoolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemPoolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "validator.MemPoolService",
	HandlerType: (*MemPoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Gossip",
			Handler:    _MemPoolService_Gossip_Handler,
		},
		{
			MethodName: "Indulge",
			Handler:    _MemPoolService_Indulge_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _MemPoolService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mempool.proto",
}
